# This file serves as the file cleaner

In [7]:
import pandas as pd

df = pd.read_csv('../data/phreeqc_example8_all_simulations.csv')
df = df.dropna()
df

,sim,specified_pH,input_Zn_mol_L,time_days,pH,TOT-H+,TOT-Zn++,TOT-Na+,TOT-NO3-,TOT-Fe+++,...,Zn(OH)4--,ZnOH+,>FeOH_str,>FeOH_weak,>FeO-_str,>FeOH2+_str,>FeOHZn+_str,>FeO-_w,>FeOH2+_w,>FeOHZn+_w
0,ph5p00_zn1e-07,5.00,1.000000e-07,365.0,4.996352,1.210717e-05,9.960889e-08,0.099988,0.1,2.598771e-09,...,2.735187e-29,5.632359e-12,2.460044e-06,0.000098,4.406788e-08,3.146036e-06,3.753899e-10,0.000002,0.000126,1.572430e-11
1,ph5p25_zn1e-07,5.25,1.000000e-07,365.0,5.246200,6.809139e-06,9.893112e-08,0.099993,0.1,4.630258e-10,...,2.712653e-28,9.943835e-12,2.842421e-06,0.000114,6.756176e-08,2.739528e-06,1.025903e-09,0.000003,0.000110,4.297787e-11
2,ph5p50_zn1e-07,5.50,1.000000e-07,365.0,5.496210,3.826110e-06,9.713167e-08,0.099996,0.1,8.246151e-11,...,2.663356e-27,1.736033e-11,3.181967e-06,0.000127,9.795688e-08,2.367862e-06,2.752968e-09,0.000004,0.000095,1.153646e-10
3,ph5p75_zn1e-07,5.75,1.000000e-07,365.0,5.746311,2.145994e-06,9.255899e-08,0.099998,0.1,1.469433e-11,...,2.539981e-26,2.942092e-11,3.470281e-06,0.000139,1.353890e-07,2.037727e-06,7.141510e-09,0.000005,0.000082,2.995013e-10
4,ph6p00_zn1e-07,6.00,1.000000e-07,365.0,5.996474,1.197283e-06,8.206505e-08,0.099999,0.1,2.622948e-12,...,2.254839e-25,4.639287e-11,3.703137e-06,0.000149,1.794382e-07,1.750752e-06,1.721183e-08,0.000007,0.000070,7.231203e-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,ph7p00_zn1e-04,7.00,1.000000e-04,365.0,7.000390,-4.445536e-07,7.142152e-05,0.099858,0.1,2.813095e-15,...,2.023826e-18,4.052048e-07,3.973951e-08,0.000156,5.598490e-09,6.462107e-09,5.598739e-06,0.000022,0.000025,2.297974e-05
74,ph7p25_zn1e-04,7.25,1.000000e-04,365.0,7.250868,-8.165159e-07,5.770633e-05,0.099885,0.1,5.383830e-16,...,1.634481e-17,5.800511e-07,2.305543e-08,0.000144,4.783967e-09,2.545413e-09,5.620155e-06,0.000030,0.000016,3.667352e-05
75,ph7p50_zn1e-04,7.50,1.000000e-04,365.0,7.501363,-1.320143e-06,4.378814e-05,0.099914,0.1,1.079679e-16,...,1.234675e-16,7.765502e-07,1.473125e-08,0.000126,4.646841e-09,1.069847e-09,5.630091e-06,0.000040,0.000009,5.058177e-05
76,ph7p75_zn1e-04,7.75,1.000000e-04,365.0,7.751892,-2.058269e-06,3.134436e-05,0.099939,0.1,2.309149e-17,...,8.725713e-16,9.724032e-07,1.000640e-08,0.000107,4.775784e-09,4.802985e-10,5.635277e-06,0.000051,0.000005,6.302036e-05
77,ph8p00_zn1e-04,8.00,1.000000e-04,365.0,8.002439,-3.194208e-06,2.122463e-05,0.099961,0.1,5.340686e-18,...,5.728837e-15,1.131055e-06,7.113477e-09,0.000088,4.995917e-09,2.320324e-10,5.638198e-06,0.000062,0.000003,7.313718e-05

In [8]:
df = df.rename(columns={'specified_pH':'input_pH','input_Zn_mol_L':'Zn','SURF-H+':'H_sorbed','SURF-Zn++':'Zn_sorbed'})
df['H']=10**(-df['input_pH'])
df

,sim,input_pH,Zn,time_days,pH,TOT-H+,TOT-Zn++,TOT-Na+,TOT-NO3-,TOT-Fe+++,...,ZnOH+,>FeOH_str,>FeOH_weak,>FeO-_str,>FeOH2+_str,>FeOHZn+_str,>FeO-_w,>FeOH2+_w,>FeOHZn+_w,H
0,ph5p00_zn1e-07,5.00,1.000000e-07,365.0,4.996352,1.210717e-05,9.960889e-08,0.099988,0.1,2.598771e-09,...,5.632359e-12,2.460044e-06,0.000098,4.406788e-08,3.146036e-06,3.753899e-10,0.000002,0.000126,1.572430e-11,1.000000e-05
1,ph5p25_zn1e-07,5.25,1.000000e-07,365.0,5.246200,6.809139e-06,9.893112e-08,0.099993,0.1,4.630258e-10,...,9.943835e-12,2.842421e-06,0.000114,6.756176e-08,2.739528e-06,1.025903e-09,0.000003,0.000110,4.297787e-11,5.623413e-06
2,ph5p50_zn1e-07,5.50,1.000000e-07,365.0,5.496210,3.826110e-06,9.713167e-08,0.099996,0.1,8.246151e-11,...,1.736033e-11,3.181967e-06,0.000127,9.795688e-08,2.367862e-06,2.752968e-09,0.000004,0.000095,1.153646e-10,3.162278e-06
3,ph5p75_zn1e-07,5.75,1.000000e-07,365.0,5.746311,2.145994e-06,9.255899e-08,0.099998,0.1,1.469433e-11,...,2.942092e-11,3.470281e-06,0.000139,1.353890e-07,2.037727e-06,7.141510e-09,0.000005,0.000082,2.995013e-10,1.778279e-06
4,ph6p00_zn1e-07,6.00,1.000000e-07,365.0,5.996474,1.197283e-06,8.206505e-08,0.099999,0.1,2.622948e-12,...,4.639287e-11,3.703137e-06,0.000149,1.794382e-07,1.750752e-06,1.721183e-08,0.000007,0.000070,7.231203e-10,1.000000e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,ph7p00_zn1e-04,7.00,1.000000e-04,365.0,7.000390,-4.445536e-07,7.142152e-05,0.099858,0.1,2.813095e-15,...,4.052048e-07,3.973951e-08,0.000156,5.598490e-09,6.462107e-09,5.598739e-06,0.000022,0.000025,2.297974e-05,1.000000e-07
74,ph7p25_zn1e-04,7.25,1.000000e-04,365.0,7.250868,-8.165159e-07,5.770633e-05,0.099885,0.1,5.383830e-16,...,5.800511e-07,2.305543e-08,0.000144,4.783967e-09,2.545413e-09,5.620155e-06,0.000030,0.000016,3.667352e-05,5.623413e-08
75,ph7p50_zn1e-04,7.50,1.000000e-04,365.0,7.501363,-1.320143e-06,4.378814e-05,0.099914,0.1,1.079679e-16,...,7.765502e-07,1.473125e-08,0.000126,4.646841e-09,1.069847e-09,5.630091e-06,0.000040,0.000009,5.058177e-05,3.162278e-08
76,ph7p75_zn1e-04,7.75,1.000000e-04,365.0,7.751892,-2.058269e-06,3.134436e-05,0.099939,0.1,2.309149e-17,...,9.724032e-07,1.000640e-08,0.000107,4.775784e-09,4.802985e-10,5.635277e-06,0.000051,0.000005,6.302036e-05,1.778279e-08
77,ph8p00_zn1e-04,8.00,1.000000e-04,365.0,8.002439,-3.194208e-06,2.122463e-05,0.099961,0.1,5.340686e-18,...,1.131055e-06,7.113477e-09,0.000088,4.995917e-09,2.320324e-10,5.638198e-06,0.000062,0.000003,7.313718e-05,1.000000e-08

In [12]:
data = df[['H','Zn','Zn(OH)2(aq)','Zn(OH)3-','Zn(OH)4--','ZnOH+','Zn++','Na+','NO3-','Fe+++','Fe++','O2(aq)','H_sorbed','Zn_sorbed']]
data

,H,Zn,Zn(OH)2(aq),Zn(OH)3-,Zn(OH)4--,ZnOH+,Zn++,Na+,NO3-,Fe+++,Fe++,O2(aq),H_sorbed,Zn_sorbed
0,1.000000e-05,1.000000e-07,1.813505e-15,7.349991e-22,2.735187e-29,5.632359e-12,9.960327e-08,0.099988,0.1,2.595839e-09,2.932403e-12,0.000246,0.000127,3.911142e-10
1,5.623413e-06,1.000000e-07,5.691547e-15,4.100588e-21,2.712653e-28,9.943835e-12,9.892119e-08,0.099993,0.1,4.620980e-10,9.279570e-13,0.000246,0.000110,1.068880e-09
2,3.162278e-06,1.000000e-07,1.767034e-14,2.263971e-20,2.663356e-27,1.736033e-11,9.711431e-08,0.099996,0.1,8.216810e-11,2.934319e-13,0.000246,0.000093,2.868332e-09
3,1.778279e-06,1.000000e-07,5.326525e-14,1.213867e-19,2.539981e-26,2.942092e-11,9.252954e-08,0.099998,0.1,1.460159e-11,9.274816e-14,0.000246,0.000078,7.441011e-09
4,1.000000e-06,1.000000e-07,1.494178e-13,6.057492e-19,2.254839e-25,4.639287e-11,8.201853e-08,0.099999,0.1,2.593642e-12,2.930748e-14,0.000246,0.000065,1.793495e-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1.000000e-07,1.000000e-04,1.316767e-08,5.387018e-13,2.023826e-18,4.052048e-07,7.100316e-05,0.099858,0.1,2.525205e-15,2.878914e-16,0.000246,-0.000025,2.857848e-05
74,5.623413e-08,1.000000e-04,3.355708e-08,2.443962e-12,1.634481e-17,5.800511e-07,5.709272e-05,0.099885,0.1,4.475472e-16,9.083606e-17,0.000246,-0.000056,4.229367e-05
75,3.162278e-08,1.000000e-04,7.998149e-08,1.037024e-11,1.234675e-16,7.765502e-07,4.293160e-05,0.099914,0.1,7.930960e-17,2.865834e-17,0.000246,-0.000087,5.621186e-05
76,1.778279e-08,1.000000e-04,1.783203e-07,4.116453e-11,8.725713e-16,9.724032e-07,3.019360e-05,0.099939,0.1,1.405128e-17,9.040222e-18,0.000246,-0.000115,6.865564e-05
77,1.000000e-08,1.000000e-04,3.693087e-07,1.517938e-10,5.728837e-15,1.131055e-06,1.972411e-05,0.099961,0.1,2.489184e-18,2.851506e-18,0.000246,-0.000138,7.877537e-05

In [13]:
data.to_csv('../data/data.csv')